services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: kpo-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      # Настройте параметры подключения к базе данных, используя имя сервиса "db"
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/kpo-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    ports:
      - "3000:80"

volumes:
  postgres_data: